### ISSUE TITLE
What's the LICENSE of the repo?

### ISSUE THREAD

**Issue by seanballais** [AndreyMlashkin/windows-clang-conan#1]
Hey, Andrei! I was just wondering what the license of the repo is. I'm basing a profile for my own project on your [profile](https://github.com/AndreyMlashkin/windows-clang-conan/blob/main/profile) file.

**Comment by AndreyMlashkin** [comment]
It's free. I will add it later today, thanks for reminding!

**Comment by AndreyMlashkin** [comment]
Done.
If you want to use it, you can simply fork it :)
and create a merge request here, it would be interesting to collaborate

**Comment by seanballais** [comment]
Thanks, @AndreyMlashkin! Thanks. I'll see if I can spare some to collaborate. I'm looking forward to it though!
